namespace WPFTest.Utils
{
    public enum LoadLibraryFlags : uint
	{
		DONT_RESOLVE_DLL_REFERENCES = 1u,
		LOAD_IGNORE_CODE_AUTHZ_LEVEL = 16u,
		LOAD_LIBRARY_AS_DATAFILE = 2u,
		LOAD_LIBRARY_AS_DATAFILE_EXCLUSIVE = 64u,
		LOAD_LIBRARY_AS_IMAGE_RESOURCE = 32u,
		LOAD_LIBRARY_SEARCH_APPLICATION_DIR = 512u,
		LOAD_LIBRARY_SEARCH_DEFAULT_DIRS = 4096u,
		LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR = 256u,
		LOAD_LIBRARY_SEARCH_SYSTEM32 = 2048u,
		LOAD_LIBRARY_SEARCH_USER_DIRS = 1024u,
		LOAD_WITH_ALTERED_SEARCH_PATH = 8u
	}
}
